<?php
error_reporting(1);

$fName=$_POST['fnamn'];
$lName=$_POST['enamn'];
$email=$_POST['epost'];
$tel=$_POST['tel'];
$adults=$_POST['adults'];
$kids=$_POST['children'];
$room=$_POST['room'];
$arrival=$_POST['arrival'];
$departure=$_POST['departure'];
$msg=$_POST['msg'];
$newsletter=$_POST['newsletter'];

echo "
<table>
   <tr>
     <th>Kontakt</th>
   </tr>
   <tr>
     <td>Förnamn</td>
     <td>$fName</td>
   </tr>
   <tr>
     <td>efternamn</td>
     <td>$lName</td>
   </tr>
   <tr>
     <td>epost</td>
     <td>$email</td>
   </tr>
   <tr>
     <td>telefon nr.</td>
     <td>$tel</td>
   </tr>
   <tr>
     <th>Rum-detaljer</th>
   </tr>
   <tr>
     <td>vuxna</td>
     <td>$adults</td>
   </tr>
   <tr>
     <td>barn</td>
     <td>$kids</td>
   </tr>
   <tr>
     <td>rumtyp</td>
     <td>$room</td>
   </tr>
   <tr>
     <td>ankomst</td>
     <td>$arrival</td>
   </tr>
   <tr>
     <td>avfärd</td>
     <td>$departure</td>
   </tr>
   <tr>
     <td>meddelande</td>
     <td>$msg</td>
   </tr>
   <tr>
     <td>nyhetsbrev</td>
     <td>$newsletter</td>
   </tr>

</table>
";